cc_library(
    name = "merlin_engine",
    srcs = glob(["src/*.cpp", "include/*.hpp"]),
    hdrs = ["include/game.hpp"],
    include_prefix = "merlin",
    strip_include_prefix = "include",
    visibility = ["//visibility:public"]
)
